namespace Week12;
using System.Data;
using MySql.Data;
using MySql.Data.MySqlClient;
class Program
{
    static void Main(string[] args)
    {
        MySqlConnection conn = new MySqlConnection(connStr);
        /*
        try
        {
            Console.WriteLine("Connecting to MySQL...");
            conn.Open();
            // Find all users whose roles are Engineering;
            // We put SQL Comman in "", the string value in SQL is in ''
            string sql = "SELECT username, password, role FROM User WHERE role='Engineering'";
            // the SQL query to be executed is passed to the MySqlCommand
            MySqlCommand cmd = new MySqlCommand(sql, conn);
           
            // ExecuteReader to query the database.
            // The MySqlReader object contains the results generated by the SQL executed on the MySqlCommand object.
            MySqlDataReader rdr = cmd.ExecuteReader();

            // the information stored in MySqlReader is printed out by a while loop
            while (rdr.Read())
            {
                Console.WriteLine($"Username: {rdr[0]} -- Password: {rdr[1]} -- Role: {rdr[2]}");
            }
            // MySqlReader object is disposed of by invoking the Close method
            rdr.Close();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }

        conn.Close();
        Console.WriteLine("Done.");
        
        try
        {
            Console.WriteLine("Connecting to MySQL...");
            conn.Open();
           
            // The parameter is preceded by an '@' symbol to indicate it is to be treated as a parameter.
            string sql = "SELECT username, role FROM User WHERE username = @username AND role= @role";
            MySqlCommand cmd = new MySqlCommand(sql, conn);

            Console.WriteLine("Please Input username: ");
            string? username_input = Console.ReadLine();           
            // get a role value from keyboard
            Console.WriteLine("Enter a role e.g.:Engineering, Support, Services, Training");
            string? user_input = Console.ReadLine();

            // assign input value to the SQL command
            cmd.Parameters.AddWithValue("@role", user_input);
            cmd.Parameters.AddWithValue("@username", username_input);
            MySqlDataReader rdr = cmd.ExecuteReader();

            while (rdr.Read())
            {   // select columon based on column name
                Console.WriteLine($"Username: {rdr["username"]} -- Role: {rdr["role"]}");
            }
            rdr.Close();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }

        conn.Close();
        Console.WriteLine("Done.");
    try
        {
            Console.WriteLine("Connecting to MySQL...");
            conn.Open();
           
            string sql = "INSERT INTO User VALUES (@username, @password, @role)";
            MySqlCommand cmd = new MySqlCommand(sql, conn);
            // input information for new record
            Console.WriteLine("Enter Username:");
            string? input_username = Console.ReadLine();
            Console.WriteLine("Enter Password:");
            string? input_password = Console.ReadLine();
            Console.WriteLine("Enter Role:");
            string? input_role = Console.ReadLine();
            // assign input values to the SQL command
            cmd.Parameters.AddWithValue("@username", input_username);
            cmd.Parameters.AddWithValue("@password", input_password);
            cmd.Parameters.AddWithValue("@role", input_role );
           
            // ExecuteNonQuery to insert, update, and delete data.
            cmd.ExecuteNonQuery();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }

        conn.Close();
        Console.WriteLine("Done.");   
    */
    try
       {
           Console.WriteLine("Connecting to MySQL...");
           conn.Open();
            // input information for new record
           Console.WriteLine("Enter Username:");
           string? input_username = Console.ReadLine();
           Console.WriteLine("Enter Password:");
           string? input_password = Console.ReadLine();
           // sql: count how many records match inputUsername and inputPassword
           // save the counted number into variable countUser
           string sql = @"SELECT COUNT(*) AS countUser FROM User
                   WHERE
                   User.username = @inputUsername
                   AND
                   User.password = @inputPassword;";
           MySqlCommand cmd = new MySqlCommand(sql, conn);
           cmd.Parameters.AddWithValue("@inputUsername", input_username);
           cmd.Parameters.AddWithValue("@inputPassword", input_password);
           MySqlDataReader rdr = cmd.ExecuteReader();
           while (rdr.Read())
           {   // if countUser equals to 1, means can find input values in table
               if(rdr["countUser"].ToString() == "1"){
                   Console.WriteLine("Login Successfully!");
               }
               else{
                   Console.WriteLine("Login Failed!");
               }
           }
          rdr.Close();
           // convert returned value to int datatype
       }

       catch (Exception ex)
       {
           Console.WriteLine(ex.ToString());
       }

       conn.Close();
       Console.WriteLine("Done.");
}
}
